- name: create user group
  group:
    name: "{{ consul_user_name }}"

- name: create consul user
  user:
    name: "{{ consul_user_name }}"
    group: "{{ consul_group_name }}"
  register: consul_user_facts

- name: set uid to be used inside the container
  set_fact:
    consul_user_id: "{{ consul_user_facts.uid }}"
