---

- name: install bind
  apt:
    name: bind9
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: ensure custom network is present
  docker_network:
    name: "{{ bind_network_name }}"
    driver: bridge
    state: present
  register: bind_docker_network_facts

- name: lookup gateway
  set_fact:
    bind_docker_bridge_ip: |-
      {{ (bind_docker_network_facts
         .ansible_facts
         .docker_network
         .IPAM
         .Config
         |first
         ).Gateway
      }}

- name: render config templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
  with_items:
    - named.conf.options
    - consul.conf

- name: restart bind
  systemd:
    name: bind9
    state: restarted
