---

- name: install/update debian packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - bind9
    - jq

- name: get docker bridge IP
  shell: >
    docker network inspect {{ bind_network_name }}
    | jq -r '.[].IPAM.Config
    | .[].Gateway'
    | cut -d/ -f1
  register: bind_docker_bridge_ip_result

- name: register docker bridge IP
  set_fact:
    bind_docker_bridge_ip: "{{ bind_docker_bridge_ip_result.stdout }}"

- name: render config templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
  with_items:
    - named.conf.options
    - consul.conf

- name: restart bind
  systemd:
    name: bind9
    state: restarted
