---

- name: install/update python-setuptools
  apt:
    name: python-setuptools
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: install latest pip
  easy_install: name=pip
