---
- include: "os/{{ ansible_os_family }}.yml"

- name: ensure config folder is present
  file:
    path: /etc/docker
    state: directory

- name: ensure docker-py module is installed
  pip:
    name: docker-py
    version: 1.10.6
  when: dockerpy

- name: ensure daemon config file is present
  template:
    src: daemon.j2.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: ensure unit file folder is present
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: ensure unit file is present & up to date
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - reload unit
    - restart docker

- meta: flush_handlers

- name: ensure starts on system boot
  service:
    name: docker
    enabled: yes

- name: ensure vagrant user can run docker commands
  user:
    name: vagrant
    groups: docker
    append: yes
  when: vagrant

- name: create custom network
  docker_network:
    name: "{{ docker_network_name }}"
