---

consul_acl_enforce_version_8: false
consul_ca_file_name: root.cer
consul_cert_file_name: server.cer
consul_client_addr: "0.0.0.0"
consul_config_dir: "/etc/consul/config"
consul_data_dir: "/data"
consul_datacenter: dc1
consul_debug_mode: true
consul_disable_remote_exec: true
consul_disable_update_check: true
consul_dns_config_allow_stale: false
consul_dns_config_max_stale: 5s
consul_dns_config_node_ttl: 10s
consul_dns_config_only_passing: false
consul_docker_image_name: valfadeev/consul
consul_docker_image_tag: latest
consul_encrypt: false
consul_encryption_key: ""
consul_group_name: consul
consul_https_port: 8080
consul_key_file_name: server.key
consul_leave_on_terminate: true
consul_local_image: true
consul_network_name: consul
consul_raft_multiplier: 1
consul_retry_join_ec2: false
consul_retry_join_ec2_tag_key: consul_env
consul_retry_join_ec2_tag_value: dev
consul_root_certificate: ""
consul_scripts_dir: "{{ consul_config_dir }}/scripts"
consul_server_certificate: ""
consul_server_key: ""
consul_services: []
consul_skip_leave_on_interrupt: true
consul_ssl_cert_dir: "{{ consul_config_dir }}/ssl"
consul_ssl_enabled: false
consul_ui_dir: "/ui"
consul_user_name: consul
consul_verify_outgoing: true
consul_version: "0.8.3"
consul_watches: []

consul_ports:
  consul_server_rpc:    8300 # tcp
  consul_serf_lan:      8301 # tcp and udp
  consul_serf_wan:      8302 # tcp and udp
  consul_cli_rpc:       8400 # tcp
  consul_http_api:      8500 # tcp
  consul_dns_interface: 8600 # tcp and udp

consul_docker_port_mappings:
  - "0.0.0.0:{{ consul_ports.consul_server_rpc }}:{{ consul_ports.consul_server_rpc }}"
  - "0.0.0.0:{{ consul_ports.consul_serf_lan }}:{{ consul_ports.consul_serf_lan }}"
  - "0.0.0.0:{{ consul_ports.consul_serf_lan }}:{{ consul_ports.consul_serf_lan }}/udp"
  - "0.0.0.0:{{ consul_ports.consul_serf_wan }}:{{ consul_ports.consul_serf_wan }}"
  - "0.0.0.0:{{ consul_ports.consul_serf_wan }}:{{ consul_ports.consul_serf_wan }}/udp"
  - "0.0.0.0:{{ consul_ports.consul_cli_rpc }}:{{ consul_ports.consul_cli_rpc }}"
  - "0.0.0.0:{{ consul_ports.consul_http_api }}:{{ consul_ports.consul_http_api }}"
  - "0.0.0.0:{{ consul_ports.consul_dns_interface }}:{{ consul_ports.consul_dns_interface }}"
  - "0.0.0.0:{{ consul_ports.consul_dns_interface }}:{{ consul_ports.consul_dns_interface }}/udp"

consul_checks_disk_warning:   30%
consul_checks_disk_critical:  5%
consul_checks_inode_warning:  30%
consul_checks_inode_critical: 5%
consul_checks_swap_warning:   20%
consul_checks_swap_critical:  5%

consul_checks_common:
    - id: "common.node.disk-util"
      name: "Disk Utilization"
      notes: "Disk critical {{ consul_checks_disk_critical }}, warning {{ consul_checks_disk_warning }} free. Inode critical {{ consul_checks_inode_critical }}, warning {{ consul_checks_inode_warning }} free."
      script: "/usr/lib/monitoring-plugins/check_disk -w {{ consul_checks_disk_warning }} -c {{ consul_checks_disk_critical }} -W {{ consul_checks_inode_warning }} -K {{ consul_checks_inode_critical }} /"
      status: "passing"
      interval: "1m"
      timeout: "20s"
    - id: "common.node.swap-util"
      name: "Swap Utilization"
      notes: "Critical {{ consul_checks_swap_critical }}, warning {{ consul_checks_swap_warning }} free"
      script: "/usr/lib/monitoring-plugins/check_swap -w {{ consul_checks_swap_warning }} -c {{ consul_checks_swap_critical }}"
      status: "passing"
      interval: "1m"
      timeout: "20s"

consul_watches_common: []

consul_checks_all: "{{ (consul_checks_common|default([]))|union(consul_checks|default([])) }}"

consul_watches_all: "{{ (consul_watches_common|default([]))|union(consul_watches|default([])) }}"
